import uuid
import secrets
from django.db import models
from backend_solvro_alerts.services import hashing


class Application(models.Model):
    """
    Application Model

    This model is a representation of an application that receives alert messages.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    api_key = models.CharField(max_length=255, unique=True) # hashed api key is stored in db

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def generate_api_key(self):
        """
        Function returns API key in a form of a plain text\n
        `self.api_key` field is assigned a hash of a returned value
        """

        # random key - generated by safe cryptographic function
        plain_text_key = secrets.token_hex(64)

        # api key is assigned a hash value
        self.api_key = hashing.hash_string(plain_text_key)

        return plain_text_key   
    
    
    def verify_api_key(self, plain_text_key:str):
        """
        Verifies if provided plain text key matches stored hash.
        """

        # value is hashed by default alghoritm
        key_hash = hashing.hash_string(plain_text_key)

        # 'compare_digest' prevents from timing attacks
        return secrets.compare_digest(self.api_key, key_hash)


    def __str__(self):
        return f"Application(name = '{self.name}')"

