# Generated by Django 6.0.4 on 2026-05-01 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL. When set, frontends should make the entire alert banner clickable and navigate here on click.",
                        max_length=500,
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("is_global", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_dismissable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applications",
                    models.ManyToManyField(
                        blank=True, related_name="alerts", to="applications.application"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_at__isnull", True),
                            ("start_at__isnull", True),
                            ("end_at__gt", models.F("start_at")),
                            _connector="OR",
                        ),
                        name="alert_end_after_start",
                    )
                ],
            },
        ),
    ]
