# Generated by Django 6.0.4 on 2026-05-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="open_in_new_tab",
            field=models.BooleanField(
                default=True,
                help_text='If true, frontends should open the link in a new tab (target="_blank" rel="noopener"). Ignored when link is empty.',
            ),
        ),
    ]
